### PR TITLE
Fix Elsa Studio Blazor Server docs

### PR DESCRIPTION
**Pull request by PKEnergy**
Update docs

### CODE REVIEW

**Review by sfmskywalker — APPROVED** [review]
Thanks!

**Comment by PKEnergy** [comment]
I accept the CLA.

**Comment by sfmskywalker** [comment]
Thank you. Please comment with one of the following commands as [described here](https://github.com/microsoft/contributorlicenseagreement#accepting):


```
If you are contributing on behalf of yourself:
@microsoft-github-policy-service agree

If you are contributing on behalf of a company:
@microsoft-github-policy-service agree company="your company"
```

**Comment by PKEnergy** [comment]
@microsoft-github-policy-service agree

**Comment by PKEnergy** [comment]
@microsoft-github-policy-service rerun

**Comment by sfmskywalker** [comment]
@microsoft-github-policy-service rerun

**Comment by sfmskywalker** [comment]
Let's give the CLA bot some time and see if it picks up the command or not.

**Pull request closed without merging**
